src/Entity/Animal.php
<?php

namespace App\Entity;

use App\Repository\AnimalRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Uid\UuidV7;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: AnimalRepository::class)]
#[Vich\Uploadable]
class Animal
{
    #[ORM\Id]
    #[ORM\GeneratedValue('CUSTOM')]
    #[ORM\Column(type: 'uuid',unique:true)]
    #[ORM\CustomIdGenerator('doctrine.uuid_generator')]
    private ?UuidV7 $id = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom_animal = null;
    // #[ORM\ManyToOne(targetEntity: Patient::class, inversedBy: 'animals')]
    // #[ORM\JoinColumn(name: "patient_id", referencedColumnName: "id", nullable: false)]
    // private ?Patient $patient = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_naissance_animal = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation_animal = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $date_fin_animal = null;

    #[Vich\UploadableField(mapping: 'animal_images', fileNameProperty: 'imageAnimal')]
    private ?File $imageFile = null;

    #[ORM\Column(nullable: true)]
    private ?string $imageAnimal = null;

    #[ORM\ManyToOne(inversedBy: 'animals')]
    private ?Race $race = null;

    #[ORM\ManyToOne(inversedBy: 'animals')]
    private ?User $user = null;

    #[ORM\OneToMany(targetEntity: Rdv::class, mappedBy: 'animal')]
    private Collection $rdvs;

    #[ORM\OneToMany(targetEntity: Soigner::class, mappedBy: 'animal')]
    private Collection $soigners;

    public function __construct()
    {
        $this->rdvs = new ArrayCollection();
        $this->soigners = new ArrayCollection();
    }



    public function getId(): ?UuidV7
    {
        return $this->id;
    }

    public function getPrenomAnimal(): ?string
    {
        return $this->prenom_animal;
    }

    public function setPrenomAnimal(string $prenom_animal): static
    {
        $this->prenom_animal = $prenom_animal;

        return $this;
    }

    public function getDateNaissanceAnimal(): ?\DateTimeInterface
    {
        return $this->date_naissance_animal;
    }

    public function setDateNaissanceAnimal(?\DateTimeInterface $date_naissance_animal): static
    {
        $this->date_naissance_animal = $date_naissance_animal;

        return $this;
    }

    public function getDateCreationAnimal(): ?\DateTimeInterface
    {
        return $this->date_creation_animal;
    }

    public function setDateCreationAnimal(\DateTimeInterface $date_creation_animal): static
    {
        $this->date_creation_animal = $date_creation_animal;

        return $this;
    }

    public function getDateFinAnimal(): ?\DateTimeInterface
    {
        return $this->date_fin_animal;
    }

    public function setDateFinAnimal(\DateTimeInterface $date_fin_animal=null): self
    {
        $this->date_fin_animal = $date_fin_animal;

        return $this;
    }

    public function getRace(): ?Race
    {
        return $this->race;
    }

    public function setRace(?Race $race): static
    {
        $this->race = $race;

        return $this;
    }



      /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageAnimal(?string $imageAnimal): void
    {
        $this->imageAnimal = $imageAnimal;
    }

    public function getImageAnimal(): ?string
    {
        return $this->imageAnimal;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Rdv>
     */
    public function getRdvs(): Collection
    {
        return $this->rdvs;
    }

    public function addRdv(Rdv $rdv): static
    {
        if (!$this->rdvs->contains($rdv)) {
            $this->rdvs->add($rdv);
            $rdv->setAnimal($this);
        }

        return $this;
    }

    public function removeRdv(Rdv $rdv): static
    {
        if ($this->rdvs->removeElement($rdv)) {
            // set the owning side to null (unless already changed)
            if ($rdv->getAnimal() === $this) {
                $rdv->setAnimal(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Soigner>
     */
    public function getSoigners(): Collection
    {
        return $this->soigners;
    }

    public function addSoigner(Soigner $soigner): static
    {
        if (!$this->soigners->contains($soigner)) {
            $this->soigners->add($soigner);
            $soigner->setAnimal($this);
        }

        return $this;
    }

    public function removeSoigner(Soigner $soigner): static
    {
        if ($this->soigners->removeElement($soigner)) {
            // set the owning side to null (unless already changed)
            if ($soigner->getAnimal() === $this) {
                $soigner->setAnimal(null);
            }
        }

        return $this;
    }

}

src/Controller/RdvEmployerController.php
<?php

namespace App\Controller;

use App\Entity\Ajouter;
use App\Entity\Animal;
use App\Entity\Employer;
use App\Entity\Rdv;
use App\Entity\Soigner;
use App\Form\RdvType;
use App\Form\SoignerType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class RdvEmployerController extends AbstractController
{
    private Security $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }
    #[Route('/rdv/employer/{jours}', name: 'app_rdv_employer')]
    public function rdvEmployer(Request $request,EntityManagerInterface $entityManager,$jours): Response
    {

      $societe=null;    
     $animal=null;
     $patient=null;
      $employer=null;
      $dates=null;
        $user = $this->security->getUser();
        $employer = $entityManager->getRepository(Employer::class)->findOneBy(['user' => $user]);
        $employerId = $employer->getId();
        if ($employerId) {

            $ajouter = $entityManager->getRepository(Ajouter::class)->findOneBy(['employer' => $employer]);

            $joursTravailArray = $ajouter->getJoursTravailler();

            $joursTravailNumerique = array_map(function ($jour) {
                return ['dimanche' => 0, 'lundi' => 1, 'mardi' => 2, 'mercredi' => 3, 'jeudi' => 4, 'vendredi' => 5, 'samedi' => 6,][strtolower($jour)];
            }, $joursTravailArray);

            if ($jours=="mois"){
                $dateDebut = new \DateTime();
                $dateFin = clone $dateDebut; 
                $dateFin->modify('last day of this month');
$jours="Vos rdv jusqu'a la fin du mois";
            }else{
                $dateDebut = new \DateTime();
                $dateFin = clone $dateDebut;
                $dateFin->modify('+'.$jours. 'days');
                $jours="Vos rdv pour les 7 prochains jours";
            }
        
            while ($dateDebut <= $dateFin) {
                if (in_array((int) $dateDebut->format('w'), $joursTravailNumerique)) {
                    $dateTravail = $dateDebut->format('Y-m-d');
                    $rdvs = $entityManager->getRepository(Rdv::class)->findBy(['date_rdv' => $dateDebut, 'employer' => $employer, 'status_rdv' => null]);


                    for ($heure = 8; $heure <= 17; $heure++) {
                        $creneauxDisponibles[$dateTravail][sprintf("%02d:00 - %02d:00", $heure, $heure + 1)] = 'Libre';
                    }


                    foreach ($rdvs as $rdv) {
                        $heureRdv = (int) $rdv->getHeureRdv()->format('H'); 

                        
                        $creneauKey = sprintf("%02d:00 - %02d:00", $heureRdv, $heureRdv + 1);

                     
                        if (isset ($creneauxDisponibles[$dateTravail][$creneauKey])) {
                           
                            $patient = $rdv->getPatient();
                            $userPatient = $patient->getUser();
                           
                                $animal = $rdv->getAnimal();
                            
                                $animalPatient = $animal->getPrenomAnimal();
                                $race = $animal->getRace();
                                $type = $race->getType();
                           
                           
                            $societe=$rdv->getSociete();
                           

                            $infoPatient = [
                                $patient->getId(),
                                $patient->getTelephonePatient(),
                                $userPatient->getEmail(),
                                $userPatient->getNom(),
                                $userPatient->getPrenom(),
                                $animalPatient,
                                $race->getRaceAnimal(),
                                $type->getTypeAnimal(),
                               $societe->getId(),
                                $employerId,
                                $animal->getId(),
                            ];
                       


                           
                            $creneauxDisponibles[$dateTravail][$creneauKey] = [
                                'status' => 'Pris',
                                'rdv' => $rdv,
                                'infoPatient' => $infoPatient,
                            ];
                        }
                    }
                }
                $dateDebut->modify('+1 day');
            }

        }
    
        $dates = new \DateTime();

        $soigner=new Soigner();
        $soigner->setSociete($societe);
      $soigner->setAnimal($animal);
      $soigner->setPatient($patient);
      $soigner->setEmployer($employer);
      $soigner->setDateSoins($dates);
        $form = $this->createForm(SoignerType::class,$soigner,[
      
        ]);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            $entityManager->persist($soigner);
            $entityManager->flush();
          
        }

        return $this->render('rdv_employer/index.html.twig', [
            'controller_name' => 'RdvEmployerController',
            'creneauxDisponible'=>$creneauxDisponibles,
            'jours'=>$jours,
            'form'=>$form,
        ]);
    }
 
    #[Route('/rdv/employer/{id}/edit/{status}', name: 'app_rdv_employer_annuler', methods: ['GET', 'POST'])]
    public function editRdvEmployer(Request $request,Rdv $rdv,EntityManagerInterface $entityManager, string $status): Response
    {
        if ($status === 'annuler') {
           
            $rdv->setStatusRdv('annuler');
            
        }else if($status === 'valider'){
            $rdv->setStatusRdv('valider');
        }
      
$entityManager->flush();
return $this->redirectToRoute('app_rdv_employer', [], Response::HTTP_SEE_OTHER);

    }


}

templates/rdv_employer/ajouterrdv.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créneaux RDV
{% endblock %}

{% block body %}
	<div class="container mt-5">
		<div class="card custom-box-shadow p-3 mb-5 bg-body rounded">
			<div class="row">
				<div class="col-12 justify-content-center text-center">
					<h1>
						Ajouter un RDV
					</h1>
				</div>
			</div>
		</div>


		<div class="row justify-content-center mb-5 ">
			<div class="col-lg-6 justify-content-center text-center">
				<div class="card custom-box-shadow rounded">
					<div class="d-flex align-items-center justify-content-center">
						<label class="mb-0">Nom:</label>
						<p class="mb-0 ml-2">{{ rechercher.nom }}</p>
					</div>
					<div class="d-flex align-items-center justify-content-center">
						<label class="mb-0">Prenom:</label>
						<p class="mb-0 ml-2">{{ rechercher.Prenom }}</p>
					</div>
					<div class="d-flex align-items-center justify-content-center">
						<label class="mb-0">Email:</label>
						<p class="mb-0 ml-2">{{ rechercher.email }}</p>
					</div>

					{{ form_errors(form) }}
					{{ form_start(form) }}
					{{ form_row(form.date_rdv, {'attr': {'readonly': 'readonly'}}) }}
					{{ form_row(form.heure_rdv, {'attr': {'readonly': 'readonly'}}) }}
					{{ form_row(form.status_rdv, {
                     'label_attr': {'class': 'hidden-form-rdv'},
                     'attr': {'class': 'hidden-form-rdv'}
                        }) }}
					{{ form_row(form.societe, {
                     'label_attr': {'class': 'hidden-form-rdv'},
                     'attr': {'class': 'hidden-form-rdv'}
                        }) }}
					{{ form_row(form.employer, {
                     'label_attr': {'class': 'hidden-form-rdv'},
                        'attr': {'class': 'hidden-form-rdv'}
                    }) }}
					{{ form_row(form.patient, {
                        'label_attr': {'class': 'hidden-form-rdv'},
                     'attr': {'class': 'hidden-form-rdv'}
                    }) }}

					<label for="animal-select" class="mb-5">Choisissez un animal :</label>
					<select id="animal-select" name="animal">

						{% for animal in animaux %}
							<option value="{{ animal.id }}">{{ animal.prenomAnimal }}</option>
						{% endfor %}
					</select>
					{{ form_widget(form.submit, {'attr': {'class': 'btn btn-custom rounded pill mb-5'}}) }}
					{{ form_end(form) }}
				</div>
			</div>
		</div>


	</div>
{% endblock %}

templates/rdv_employer/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créneaux RDV{% endblock %}

{% block body %}
	{{ form_errors(form) }}
		{{ form_start(form) }}
        {{ form(form) }}
        {{ form_end(form) }}

{% endblock %}

templates/rdv_employer/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créneaux RDV
{% endblock %}

{% block body %}
	{% for message in app.flashes('info') %}
		<div class="alert alert-info">
			{{ message }}
		</div>
	{% endfor %}
	<div class="container">
		<div class="card custom-box-shadow p-3 mb-5 bg-body rounded">
			<div class="row">
				<div class="col-12 justify-content-center text-center">
					<h1>
						{{jours}}
					</h1>
				</div>
			</div>
		</div>


		<div class="row">
			{% for date, heures in creneauxDisponible %}

				<div class="col-12 col-lg-4">
					<div class="card custom-box-shadow">
						<h3>{{ date }}</h3>
						<div class="jour">
							{% for heure, info in heures %}
								<div class="card">
									<div class="creneau">
										<strong>{{ heure }}</strong>
										:
										{% if info is iterable %}

											<div>

												<p>Prenom Animal:
													{{ info['infoPatient'][5] }}</p>
											</div>
											<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#detail">Détail</button>
											<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#annuler">
												Annuler le rdv
											</button>
											<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#valider">
												Valider le rdv
											</button>

											<!-- Modal -->
											{% include 'rdv_employer/modal/detail.html.twig' with {'info': info} %}
											{% include 'rdv_employer/modal/annuler.html.twig' with {'info': info} %}
											{% include 'rdv_employer/modal/valider.html.twig' with {'info': info} %}


										{% else %}
											{{ info }}
											{# <button type="button" class="btn btn-secondary"data-bs-toggle="modal" data-bs-target="#ajouter">Ajouter</button>
																				{% include 'rdv_employer/modal/ajouterrdv.html.twig' %} #}
											<div class="col-lg-12">
												<form method="POST" action="{{ path('app_rdv_employer_ajouter') }}" data-turbo="false">
													<input type="hidden" name="heure" value="{{heure|slice(0,5)}}">
													<input type="hidden" name="date" value="{{date}}">
													<p>Email :</p>

													<input type="email" name="ajouterRdv"class="form-control">


													<div class="col-lg-4">
														<input type="submit" value="Rechercher" class="btn btn-custom rounded pill">
													</div>
												</form>

											</div>

										{% endif %}
									</div>
								</div>
							{% endfor %}

						</div>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}